### ISSUE TITLE
[Feature] Option to switch on sound of videos

### ISSUE THREAD

**Issue by LEAL-original** [anufrievroman/waypaper#108]
When trying mpvpaper on its own, the video outputs sound, as expected;
However when using waypaper, the same video (or any other) doesn't have sound

PS: No messages on the terminal give any indication on the issue.

**Comment by anufrievroman** [comment]
Hi, this is by design as we assumed nobody would run wallpapers with sound. Are you one og those who need this possibility? I can add a setting for that.

**Comment by LEAL-original** [comment]
Yes ^^
I came from windows an year ago or so, and mirroring wallpaper engine's functionality is one of the last things it's yet to do 
Thanks in advance ^^

**Comment by anufrievroman** [comment]
Okay, let's keep this issue open then, I'll implement it in the next version.

**Comment by anufrievroman** [comment]
So, I made a toggle to switch the sound, but due to the way mpv and mpvpaper work, it only works flawlessly if you initially start video with sound on. Otherwise, you'd have to click Stop button, and then start the video again with the sound. I'll check their documentation a bit more on occasion to see if there is a way to start wallpaper muted but with audio track included.

**Comment by LEAL-original** [comment]
Thank you : D

I tried running it, but I'm getting this python error:
`Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
  File "/usr/lib/python3.13/site-packages/waypaper/__main__.py", line 10, in <module>
    from waypaper.app import App
  File "/usr/lib/python3.13/site-packages/waypaper/app.py", line 9, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'`

I've been of changing to nix because every time, once my config is perfect, arch messes it xD

Either way other, if you're interested another feature you can try to add is the accent-color (I imagine on linux it might have to with GTK, where you can set color for a specific wallpaper and the windows (aka Discord, etc, will follow it).

Lastly, I have a question, do you if it's possible to make use of the 4 monitors to watch one movie in fullscreen using all of them like if it were one big screen? I've a quad-monitor setup, have been searching on the mpv doc and so, but I've gotten there yet xD

Thanks, once again : D
Have a good day

**Comment by anufrievroman** [comment]
Good :)

So, I'll close this issue, but to answer your suggestions:
- Not sure what you mean by accent colors, as related to wallpapers. On Linux, there are accent colors both in gnome and KDE environments, but has to be implemented system-wide. You may take a look at pywal project, that's what people usually pair with Waypaper to get colors from wallpaper. In GUI, the color is the background color of the wallpaper, i.e. it rarely visible.
- I noticed that some files, especially videos, fail to generate previews, it is usually either first frame is black, or file is broken, or some other file-specific reason. Impossible to say without having this exact file.
- I am also not sure if stretched video across multiple monitors is supposed by mpvpaper. It seems that we always have to specify the monitor. Maybe there's something in documentation, but that's something so niche that I can't imagine even working on it, without actually have several monitors...
