### ISSUE TITLE
[bug] Waypaper wont start anymore

### ISSUE THREAD

**Issue by bknightInfo** [anufrievroman/waypaper#116]
Hi,

Waypaper no longer starts for me as it generates a error with i assume is a python error

System
OS: ArchLinux 6.12.6
Mem: 32 Gig

Waypaper: 2.4-1

Error:
Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
ModuleNotFoundError: No module named 'waypaper'

**Comment by anufrievroman** [comment]
Is this AUR installation? If so, was it -git version or regular? I think installation via pipx will fix this, but in general, this should not be a problem...

**Comment by bknightInfo** [comment]
Aur but non -git version

waypaper-git has a different problem
Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
  File "/usr/lib/python3.13/site-packages/waypaper/__main__.py", line 10, in <module>
    from waypaper.app import App
  File "/usr/lib/python3.13/site-packages/waypaper/app.py", line 9, in <module>
    import imageio
ModuleNotFoundError: No module named 'imageio'

**Comment by bknightInfo** [comment]
installing via pipx does work

**Comment by jrhrsmit** [comment]
After the update to python 3.13, you need to re-install waypaper and the python AUR dependencies
`yay -Sy python-imageio python-screeninfo`
(and probably others)

**Comment by Jagadishwar49** [comment]
> After the update to python 3.13, you need to re-install waypaper and the python AUR dependencies `yay -Sy python-imageio python-screeninfo` (and probably others)

after reinstalling waypaper is working

**Comment by anufrievroman** [comment]
Yeah, it's related to new python probably. Here's [reddit discussion](https://www.reddit.com/r/hyprland/comments/1hkr0dh/waypaper_just_wont_run_after_system_update_minor/) of this issue. So, either just reinstall waypaper, or try this:
```
pacman -Qoq /usr/lib/python3.12
yay -S $(pacman -Qoq /usr/lib/python3.12) --answerclean All
```

**Comment by anufrievroman** [comment]
So I'll assume this issue is resolved. Not sure what we can do on our side here.
