### ISSUE TITLE
Waypaper does not start due to screeninfo

### ISSUE THREAD

**Issue by DusanNikcevic** [anufrievroman/waypaper#91]
Hello guys, I am using hyprland, when I try to run waypaper I get this error:

```

Traceback (most recent call last):
  File "/usr/bin/waypaper", line 5, in <module>
    from waypaper.__main__ import run
  File "/usr/lib/python3.12/site-packages/waypaper/__main__.py", line 10, in <module>
    from waypaper.app import App
  File "/usr/lib/python3.12/site-packages/waypaper/app.py", line 11, in <module>
    from waypaper.changer import change_wallpaper
  File "/usr/lib/python3.12/site-packages/waypaper/changer.py", line 5, in <module>
    from waypaper.config import Config
  File "/usr/lib/python3.12/site-packages/waypaper/config.py", line 11, in <module>
    from waypaper.common import check_installed_backends
  File "/usr/lib/python3.12/site-packages/waypaper/common.py", line 10, in <module>
    from screeninfo import get_monitors
ModuleNotFoundError: No module named 'screeninfo'
```

I tries installing this module via pip, via pipx and via aur helpers, nothing works.

Any ideas?

**Comment by DusanNikcevic** [comment]
solved by installing `screeninfo` with `yay -S python-screeninfo  `  to get wallpapers to work

**Comment by anufrievroman** [comment]
Yes, it's a new module that was added in the latest version, and should have been installed. Did you use AUR waypaper or waypaper-git? I guess the packager didn't update the dependencies yet.

**Comment by DusanNikcevic** [comment]
I used ML4W package to get hyprland configured, then I tried using AUR to install waypaper directly. That did not work, but installing screeninfo via AUR did. So now everything is awesome. Thanks for the awesome tool!
