### ISSUE TITLE
MP4 files fail to generate previews

### ISSUE THREAD

**Issue by Decards** [anufrievroman/waypaper#93]
Hi, 

When i unselect "show gifs only", it starts "caching wallpapers..." and nothing never happens i have 2 MP4s working  with mpvpaper manually a gif and 2 pngs in my targeted folder. 

Everytime it hangs on "caching wallpapers" and i can only see the gif i have. 

when i unselect gif only  i get that in my terminal :

Exception in thread Thread-2 (process_images):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/site-packages/waypaper/app.py", line 329, in process_images
    cache_image(image_path, self.cf.cache_dir)
  File "/usr/lib/python3.12/site-packages/waypaper/app.py", line 47, in cache_image
    pixbuf = read_video_frame(str(image_path), cache_dir)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/waypaper/app.py", line 36, in read_video_frame
    pixbuf = GdkPixbuf.Pixbuf.new_from_file(temp_frame)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Must be bytes, not PosixPath

**Comment by anufrievroman** [comment]
Looks like you have a file in your folder for which it is can't build a preview. We should make an exception for this case and just make a black rectangle.

**Comment by anufrievroman** [comment]
Okay, in the recent commits I tried to fix this, not it will show a black image if preview could not be generated. I couldn't test it at the moment. Please try if you have time.

**Comment by Decards** [comment]
I  just tried it. It works flawlessly now, it's showing black placeholders for the MP4s. Thanks for your help !

**Comment by anufrievroman** [comment]
I'll reopen this issue since indeed mp4 files don't generate previews, which is a shame since this is the most popular format.

**Comment by anufrievroman** [comment]
I think it's caused just by the fact that there are new library used not yet packaged as dependencies. Anyways, I now reimplemented the preview system, now it seems to work.
