### ISSUE TITLE
Waypaper is still trying to write to the configuraiton file, even if `use_xdg_state = True` 

### ISSUE THREAD

**Issue by diegoroccia** [anufrievroman/waypaper#98]
I have the following configuration

```ini
[Settings]
language = en
folder = ~/Pictures/wallpapers
backend = hyprpaper
monitors = All
fill = Fill
sort = name
color = #ffffff
subfolders = True
number_of_columns = 3
post_command = 
show_hidden = False
show_gifs_only = False
use_xdg_state = True
```

So I would expect that the config.ini file doesn't need to be touched by the app. I am using home-manager on Ubuntu and this file is set as immutable/readonly. When I try to change wallpaper, though, this is what happens:

```bash
> ~/.local/pipx/venvs/waypaper/bin/waypaper --random
We got: en
True # <- This is just me testing that the use_xdg_state was currently set
Traceback (most recent call last):
  File "~/.local/pipx/venvs/waypaper/bin/waypaper", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "~/.local/pipx/venvs/waypaper/lib/python3.12/site-packages/waypaper/__main__.py", line 67, in run
    cf.save()
  File "~/.local/pipx/venvs/waypaper/lib/python3.12/site-packages/waypaper/config.py", line 214, in save
    with open(self.config_file, "w") as configfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '~/.config/waypaper/config.ini'
```

**Comment by anufrievroman** [comment]
I see. Yes, it tries to overwrite the config even if you use state file. To be honest, I never used the immutable systems like that, so I'm not sure what's the expected behavior is. Currently, state file only stores information about monitors and wallpaper (according to [previous discussions](https://github.com/anufrievroman/waypaper/issues/35)). But all the other settings are still stored in the config (and overwritten when changed). So, for you, the expected behavior would be that everything is stored in the state file, or just that it does not crash if permission denied? Or all the things that can be changed via GUI should be stored in the state file (which is almost all things)?

**Comment by darth62969** [comment]
I think that using state files in general might be the better option. Especially if you are using them in the first place. otherwise we should use the config file.

**Comment by jgregoire** [comment]
I manage my dotfiles with git. Every time I run `waypaper --random` it changes the file, which shows up as an annoying change in the repo.

The config file should not change if I haven't launched the GUI and changed settings. State and config should not share a file, IMO.

I would like to see either a separate state file, or a config option like `stateful = False` since I just want a random wallpaper every boot.

**Comment by darth62969** [comment]
Why are you managing your dot files in your dot files? You should keep them separate and use a script to port the changes over. 

Rule one of development, never run prod off your development server. :P

Like seriously though. copy your dot files somewhere else and then copy them over once you are done modifying them to test. This will avoid this issue entirely.

**Comment by anufrievroman** [comment]
Hmm, I thought that if we use a state file, then config.ini is not rewritten upon `--random` just to save a new wallpaper. I'll see, probably we can fix that...

**Comment by jgregoire** [comment]
> Why are you managing your dot files in your dot files? You should keep them separate and use a script to port the changes over.
> 
> Rule one of development, never run prod off your development server. :P
> 
> Like seriously though. copy your dot files somewhere else and then copy them over once you are done modifying them to test. This will avoid this issue entirely.
> 
> example script: https://github.com/darth62969/BeyondTheWired_Theme/blob/master/UpdateConfigs.sh

Thanks for the unsolicited advice.

**Comment by anufrievroman** [comment]
Hi, I updated it so that config.ini is not needlessly saved on `--random` and other non CLI commands. However, it will still be saved when something in GUI is changed, but it will fail if the permission is not there, so that GUI element will always be the same. I hope it finally concludes the state file saga :)

**Comment by anufrievroman** [comment]
I'll assume this issue is resolved, if there is still some trouble feel free to reopen. Thanks for reporting!

**Comment by jgregoire** [comment]
Just tested. All good!
